### ISSUE TITLE
Cannot read property 'style' of null

### ISSUE THREAD

**Issue by antoine92190** [mapsplugin/cordova-plugin-googlemaps#1583]
Plugin version: `2.0.0-beta2-20170724-0410`

Since 847f7a6, when I launch my project on android, I get the below error in chrome debug console:

`Uncaught TypeError: Cannot read property 'style' of null
at plugins/cordova-plugin-googlemaps/www/googlemaps-cdv-plugin.js:63`

I cannot reproduce the issue on a blank project, only on my main project.
Do you have any idea that could help me figure out what's wrong?

Thanks!

**Comment by wf9a5m75** [comment]
Oops, sorry about that. 
I didn't face that error when I tried. But It's wrong anyway.
I fixed it.

**Comment by antoine92190** [comment]
Strange, I still get the error.
I reinstalled the plugin and removed the android platform to make sure your fix was updated.

It seems the error appears from this line:
`document.body.style.backgroundImage = 'url() !important';`

As my project is heavy, is it possible that `document.body` is not yet defined when your plugin calls it?

**Comment by wf9a5m75** [comment]
I see. I changed the code. Please try again.

**Comment by antoine92190** [comment]
All good :thumbsup:
