### ISSUE TITLE
Map Not Panning To Lat Lng / Markers Sometimes Missing

### ISSUE THREAD

**Issue by KimberleeDArmstrong** [mapsplugin/cordova-plugin-googlemaps#1689]
**I'm submitting a ...**  (check one with "x")
[ ] question
[x ] any problem or bug report
[ ] feature request

**The plugin version:**  (check one with "x")
[ ] **1.4.x**
[x ] **2.0.0-beta3** 

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
[ ] **Android**
[ x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

Kimberlees-MacBook-Pro:dvLinemanAppSDK2 kimberleearmstrong$ cordova plugin ls
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-background-geolocation-lt 2.5.1 "BackgroundGeolocation"
cordova-plugin-actionsheet 2.2.2 "ActionSheet"
cordova-plugin-background-fetch 4.0.0 "CDVBackgroundFetch"
cordova-plugin-camera 2.3.0 "Camera"
cordova-plugin-cocoalumberjack 0.0.1 "CocoaLumberjack"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-file 4.3.0 "File"
cordova-plugin-file-transfer 1.6.0 "File Transfer"
cordova-plugin-googlemaps 2.0.0-beta3-20170829-1218 "cordova-plugin-googlemaps"
cordova-plugin-network-information 1.2.0 "Network Information"
cordova-plugin-urlhandler 0.7.0 "URLHandler"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-spatialite-storage 1.1.0 "Cordova sqlite/spatialite storage plugin"
phonegap-plugin-barcodescanner 6.0.6 "BarcodeScanner"
phonegap-plugin-contentsync 1.3.5 "content-sync"
phonegap-plugin-push 1.8.1 "PushPlugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 3.1.1 "Launch Navigator"

**Current behavior:**
App does not pan to marker

**Expected behavior:**
App would pan to marker

**Steps to reproduce:**
Continuously go to left side menu and click "Go To Assignment" button from various assignments in the list

**Screen capture or video record:**
http://www.youtube.com/watch?v=9W1D4-TE97k

**Related code, data or error log (please format your code or data):**
https://bitbucket.org/KimberleeArmstrong/lineman-app

insert any relevant code, data, or error log here

----

If your problem is solved, please consider small amount donation to this project.
Appreciate for your kindness.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/README.md#buy-me-a-beer

**Comment by wf9a5m75** [comment]
I noticed this occurs since last year I saw to now.
I thought this is implementation of your code, because this occurs only your app.
(You know what I checks lots of other people projects.)

Debugging your app, I always face trouble, because your app download the actual source code from your server into your app.
Is there any way to load your source code from in your app instead of downoad?

**Comment by wf9a5m75** [comment]
Regarding of `Sometimes Missing`, I fixed a bug in another issue report that might be related with this issue.
Please retry with the latest version. Thanks.

**Comment by KimberleeDArmstrong** [comment]
I have create a new repository with the code included in the project. I sent you an invite to it.  I will test latest version for missing icons.

**Comment by wf9a5m75** [comment]
Great!

**Comment by wf9a5m75** [comment]
Did you sent the invitation?

**Comment by KimberleeDArmstrong** [comment]
Yes I did. I just sent it again though. 

Regards, 

Kimberlee Armstrong 
Software Engineer 
dataVoice International Inc. 
972-390-8808 X144

**Comment by wf9a5m75** [comment]
Thank you for re-send the invitation. It worked.

Then I checked your code.
You specified `disableAutoPan: true` a lot, that's why the map not pan to the marker.

**Comment by KimberleeDArmstrong** [comment]
I thought "disableAutoPan" means when you click on the marker do not automatically pan the map to center the marker. That is not my issue. I am running the function... 

googleMap.animateCamera( { 
'target': {lat:data.lat, lng:data.lon}, 
'tilt':0, 
'zoom': parseInt(20), 
'bearing':0, 
'duration':1000 
}, function() { 
popup.trigger(plugin.google.maps.event.MARKER_CLICK); 
fixTitlesBySvcIdx(service_index); 
}); 

In the video I made of the issue you can see that I am sending a valid lat/lon to the animateCamera function and it doesn't do anything. 

Regards, 

Kimberlee Armstrong 
Software Engineer 
dataVoice International Inc. 
972-390-8808 X144

**Comment by KimberleeDArmstrong** [comment]
FYI I just make changes to the project.  I changed the server it needs to point to.

**Comment by wf9a5m75** [comment]
Status: confirmed.

**Comment by wf9a5m75** [comment]
Very strange. The issue happens from the third time certainly, and the native code is not executed at the third time.

**Comment by wf9a5m75** [comment]
Ok, I got the reason.

**Comment by wf9a5m75** [comment]
Fixed.

![1689](https://user-images.githubusercontent.com/167831/29900101-528b294c-8da4-11e7-93ca-a68e6d5892fe.gif)

**Comment by KimberleeDArmstrong** [comment]
When I downloaded the latest plugin to try it out, I couldn't get it to work.  Instead of getting a map, I am getting a white screen.  No "Google", No location target symbol.  I was able to reproduce on BitBucket Repository by updating to the latest plugin.  I saw some error about no access to InverseDeviceID, but I am not sure if that is related or not.

Screen shot of error:
![screen shot 2017-09-01 at 1 38 28 pm](https://user-images.githubusercontent.com/9216004/29983881-697b8140-8f1d-11e7-8e32-67051b8e843d.png)

Video of app issue:
http://www.youtube.com/watch?v=NH-UC77e7UE

**Comment by wf9a5m75** [comment]
Could you show me the result of `$> cordova plugin list`?

**Comment by KimberleeDArmstrong** [comment]
Most certainly..
Kimberlees-MacBook-Pro:KimberleeArmstrong-linemanapp-d24b9e08dd56 kimberleearmstrong$ cordova plugin ls
com.googlemaps.ios 2.4.0 "Google Maps SDK for iOS"
cordova-background-geolocation-lt 2.5.1 "BackgroundGeolocation"
cordova-plugin-actionsheet 2.2.2 "ActionSheet"
cordova-plugin-background-fetch 4.0.0 "CDVBackgroundFetch"
cordova-plugin-camera 2.3.0 "Camera"
cordova-plugin-cocoalumberjack 0.0.1 "CocoaLumberjack"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-file 4.3.0 "File"
cordova-plugin-file-transfer 1.6.0 "File Transfer"
cordova-plugin-googlemaps 2.0.0-beta3-20170831-1824 "cordova-plugin-googlemaps"
cordova-plugin-network-information 1.2.0 "Network Information"
cordova-plugin-urlhandler 0.7.0 "URLHandler"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-spatialite-storage 1.1.0 "Cordova sqlite/spatialite storage plugin"
phonegap-plugin-barcodescanner 6.0.6 "BarcodeScanner"
phonegap-plugin-contentsync 1.3.5 "content-sync"
phonegap-plugin-push 1.8.1 "PushPlugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 3.1.1 "Launch Navigator"
Kimberlees-MacBook-Pro:KimberleeArmstrong-linemanapp-d24b9e08dd56 kimberleearmstrong$

**Comment by wf9a5m75** [comment]
Okay

**Comment by wf9a5m75** [comment]
Did you download the plugin today?

**Comment by KimberleeDArmstrong** [comment]
yes just prior to posting.  I have downloaded it several times over the last 24 hours and all were giving me this behavior.

**Comment by wf9a5m75** [comment]
Umm, I reproduced this issue, but I haven't changed iOS code so much after fixing this issue.

**Comment by KimberleeDArmstrong** [comment]
It worked at first and then it just stopped working and getting the white screen.  At first I thought it was  my code because it worked on one server and not the other.  Then I diffed all the source code and it was identical.  Then I moved back to working server and it didn't work either and no code had changed.  I didn't post immediately because everything pointed to not being a plugin issue, but I hit a wall trying to solve it myself.

**Comment by wf9a5m75** [comment]
Okay, thank you for your debugging. I'm checking my commit history

**Comment by wf9a5m75** [comment]
It seems this is the reason.
https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/a1781ed20b27325fa86d42b7c5943cacea4f0c1b

**Comment by KimberleeDArmstrong** [comment]
I did notice that when it was working that some marker icons were still missing and the infowindow that was popped us was fixed and didn't adjust with panning, just an FYI.

**Comment by wf9a5m75** [comment]
>some marker icons were still missing

Could you find the condition?
I didn't detect which one is missing.
(because this is not my app, I don't know all locations)

>and didn't adjust with panning

Could you explain more details?

**Comment by KimberleeDArmstrong** [comment]
Understood.  I am trying to download version b10a09f361f2a72e4e61e50d971e110efb8d1759 of the plugin so I can do that for you.

**Comment by wf9a5m75** [comment]
Okay, I fixed the issue `map is white`.
Please try again.

**Comment by KimberleeDArmstrong** [comment]
Yay!!!  Fixed.  I am not getting the info window issue with this version but I am still getting missing markers.  I am trying to make a video to help.

**Comment by KimberleeDArmstrong** [comment]
http://www.youtube.com/watch?v=5iwC_5aJx40

**Comment by wf9a5m75** [comment]
Um, strange.

**Comment by wf9a5m75** [comment]
Fixed.
![issue_1689](https://user-images.githubusercontent.com/167831/29990196-42106b9c-8f2d-11e7-940c-32ac69c0dcac.gif)
