### ISSUE TITLE
Small memory leak in iOS

### ISSUE THREAD

**Issue by minortom** [mapsplugin/cordova-plugin-googlemaps#1893]
First of all, thanks for all your effort with this plugin. While I was debugging our iOS app, we found a memory leak. I'm not that pro in debugging yet, but I think there needs to be some code added to the following file:
PluginMarker.m on line 1456

You need to add 
`[session finishTasksAndInvalidate]`

See this thread:
https://stackoverflow.com/questions/21554987/nsurlsession-memory-leaks-occur-when-using-web-services-in-ios

Thanks again for your plugin!

I have a question about the DOM analyzing. Do you check the whole DOM or only the DOM elements that are visible in the viewport?

**Comment by wf9a5m75** [comment]
Thank you for letting me know. I will test this.

**Comment by wf9a5m75** [comment]
Fixed. The code will be released in the next stable version.

**Comment by minortom** [comment]
No problem! Glad that I could help. I still have a question about the DOM watcher. Do you keep the whole DOM watched? Or only the elements that are visible in the viewport? If not, you could gain more performance by only checking elements that are visible. Thanks again for your plugin!

**Comment by wf9a5m75** [comment]
The plugin needs to know size and position of all HTML elements, in order to detect touch correctly.
