### ISSUE TITLE
Ionic build iOS return in xcode error when compiling

### ISSUE THREAD

**Issue by thezakman** [mapsplugin/cordova-plugin-googlemaps#2104]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ x ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [ x ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

I'm using the last version of your forked ```@ionic-native```:
```
    "@ionic-native/core": "file:../ionic-native/dist/@ionic-native/core",
    "@ionic-native/google-maps": "file:../ionic-native/dist/@ionic-native/google-maps"
```
**Current behavior:**

The ```ionic cordova build ios --prod``` is crashing withe the new language support strings: 

```
CopyStringsFile build/emulator/Cheeper.app/pgm_Localizable.strings Cheeper/Resources/Base.lproj/pgm_Localizable.strings
    cd /Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/cesarpinheiro/Desktop/cheeper-ios/node_modules/.bin:/usr/local/bin:/usr/local/git/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/root/Android/Sdk/tools:/root/Android/Sdk/platform-tools:/Applications/Android Studio.app/sdk/platform-tools:/Applications/Android Studio.app/sdk/tools"
    builtin-copyStrings --validate --inputencoding utf-8 --outputencoding binary --outdir /Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios/build/emulator/Cheeper.app -- Cheeper/Resources/Base.lproj/pgm_Localizable.strings

CopyStringsFile build/emulator/Cheeper.app/pgm_Localizable.strings Cheeper/Resources/ja.lproj/pgm_Localizable.strings
    cd /Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/cesarpinheiro/Desktop/cheeper-ios/node_modules/.bin:/usr/local/bin:/usr/local/git/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/root/Android/Sdk/tools:/root/Android/Sdk/platform-tools:/Applications/Android Studio.app/sdk/platform-tools:/Applications/Android Studio.app/sdk/tools"
    builtin-copyStrings --validate --inputencoding utf-8 --outputencoding binary --outdir /Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios/build/emulator/Cheeper.app -- Cheeper/Resources/ja.lproj/pgm_Localizable.strings

CopyStringsFile build/emulator/Cheeper.app/pgm_Localizable.strings Cheeper/Resources/ru.lproj/pgm_Localizable.strings
    cd /Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/cesarpinheiro/Desktop/cheeper-ios/node_modules/.bin:/usr/local/bin:/usr/local/git/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/root/Android/Sdk/tools:/root/Android/Sdk/platform-tools:/Applications/Android Studio.app/sdk/platform-tools:/Applications/Android Studio.app/sdk/tools"
    builtin-copyStrings --validate --inputencoding utf-8 --outputencoding binary --outdir /Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios/build/emulator/Cheeper.app -- Cheeper/Resources/ru.lproj/pgm_Localizable.strings

CopyStringsFile build/emulator/Cheeper.app/pgm_Localizable.strings Cheeper/Resources/uk.lproj/pgm_Localizable.strings
    cd /Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/cesarpinheiro/Desktop/cheeper-ios/node_modules/.bin:/usr/local/bin:/usr/local/git/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/root/Android/Sdk/tools:/root/Android/Sdk/platform-tools:/Applications/Android Studio.app/sdk/platform-tools:/Applications/Android Studio.app/sdk/tools"
    builtin-copyStrings --validate --inputencoding utf-8 --outputencoding binary --outdir /Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios/build/emulator/Cheeper.app -- Cheeper/Resources/uk.lproj/pgm_Localizable.strings

CopyStringsFile build/emulator/Cheeper.app/pgm_Localizable.strings Cheeper/Resources/pt-BR.lproj/pgm_Localizable.strings
    cd /Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/cesarpinheiro/Desktop/cheeper-ios/node_modules/.bin:/usr/local/bin:/usr/local/git/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/root/Android/Sdk/tools:/root/Android/Sdk/platform-tools:/Applications/Android Studio.app/sdk/platform-tools:/Applications/Android Studio.app/sdk/tools"
    builtin-copyStrings --validate --inputencoding utf-8 --outputencoding binary --outdir /Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios/build/emulator/Cheeper.app -- Cheeper/Resources/pt-BR.lproj/pgm_Localizable.strings

CopyStringsFile build/emulator/Cheeper.app/pgm_Localizable.strings Cheeper/Resources/de.lproj/pgm_Localizable.strings
    cd /Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/cesarpinheiro/Desktop/cheeper-ios/node_modules/.bin:/usr/local/bin:/usr/local/git/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/root/Android/Sdk/tools:/root/Android/Sdk/platform-tools:/Applications/Android Studio.app/sdk/platform-tools:/Applications/Android Studio.app/sdk/tools"
    builtin-copyStrings --validate --inputencoding utf-8 --outputencoding binary --outdir /Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios/build/emulator/Cheeper.app -- Cheeper/Resources/de.lproj/pgm_Localizable.strings
error: failed to remove /Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios/build/emulator/Cheeper.app/pgm_Localizable.strings: “pgm_Localizable.strings” couldn’t be removed.

CopyStringsFile build/emulator/Cheeper.app/pgm_Localizable.strings Cheeper/Resources/fr.lproj/pgm_Localizable.strings
    cd /Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/cesarpinheiro/Desktop/cheeper-ios/node_modules/.bin:/usr/local/bin:/usr/local/git/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/root/Android/Sdk/tools:/root/Android/Sdk/platform-tools:/Applications/Android Studio.app/sdk/platform-tools:/Applications/Android Studio.app/sdk/tools"
    builtin-copyStrings --validate --inputencoding utf-8 --outputencoding binary --outdir /Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios/build/emulator/Cheeper.app -- Cheeper/Resources/fr.lproj/pgm_Localizable.strings

2018-02-22 15:36:44.804 xcodebuild[8905:406272]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-13756/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/Runtime/PBXTargetBuildContext.mm:757
Details:  unexpected successful exit code from cancelled command <C0015:'CopyStringsFile pgm_Localizable.strings':P6>
Object:   <PBXTargetBuildContext: 0x7fa5ab8f6ea0>
Method:   -createCommandInvocationRecordFromInvocation:
Thread:   <NSThread: 0x7fa5a8fb78e0>{number = 13, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2018-02-22 15:36:44.805 xcodebuild[8905:406272]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-13756/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/Runtime/PBXTargetBuildContext.mm:757
Details:  unexpected successful exit code from cancelled command <C0008:'CpResource GoogleMaps.bundle':P6>
Object:   <PBXTargetBuildContext: 0x7fa5ab8f6ea0>
Method:   -createCommandInvocationRecordFromInvocation:
Thread:   <NSThread: 0x7fa5a8fb78e0>{number = 13, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
** BUILD FAILED **


The following build commands failed:
	CopyStringsFile build/emulator/Cheeper.app/pgm_Localizable.strings Cheeper/Resources/de.lproj/pgm_Localizable.strings
(1 failure)
(node:8796) UnhandledPromiseRejectionWarning: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios/cordova/build-debug.xcconfig,-workspace,Cheeper.xcworkspace,-scheme,Cheeper,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone X,build,CONFIGURATION_BUILD_DIR=/Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios/build/sharedpch
(node:8796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8796) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Expected behavior:**

The file should build without crash like it used to be.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by thezakman** [comment]
I think the error is comming from the ```fr.lproj``` because phrases like ```"Le service de localisation n'est pas disponible";``` don't close the **'**.

**Comment by wf9a5m75** [comment]
```
$> cordova clean

$> cordova build ios
```

**Comment by thezakman** [comment]
I did that, but still getting an error while running ```ionic cordova build ios --prod```:


```
CopyStringsFile build/emulator/Cheeper.app/pgm_Localizable.strings Cheeper/Resources/fr.lproj/pgm_Localizable.strings
    cd /Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/cesarpinheiro/Desktop/cheeper-ios/node_modules/.bin:/usr/local/bin:/usr/local/git/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/root/Android/Sdk/tools:/root/Android/Sdk/platform-tools:/Applications/Android Studio.app/sdk/platform-tools:/Applications/Android Studio.app/sdk/tools"
    builtin-copyStrings --validate --inputencoding utf-8 --outputencoding binary --outdir /Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios/build/emulator/Cheeper.app -- Cheeper/Resources/fr.lproj/pgm_Localizable.strings

2018-02-22 22:32:57.161 xcodebuild[13282:618204]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-13756/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/Runtime/PBXTargetBuildContext.mm:757
Details:  unexpected successful exit code from cancelled command <C0008:'CpResource GoogleMaps.bundle':P6>
Object:   <PBXTargetBuildContext: 0x7fb4d78dbd70>
Method:   -createCommandInvocationRecordFromInvocation:
Thread:   <NSThread: 0x7fb4d4c2c0b0>{number = 2, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
** BUILD FAILED **


The following build commands failed:
	CopyStringsFile build/emulator/Cheeper.app/pgm_Localizable.strings Cheeper/Resources/pt-BR.lproj/pgm_Localizable.strings
(1 failure)
(node:13252) UnhandledPromiseRejectionWarning: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios/cordova/build-debug.xcconfig,-workspace,Cheeper.xcworkspace,-scheme,Cheeper,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone X,build,CONFIGURATION_BUILD_DIR=/Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/cesarpinheiro/Desktop/cheeper-ios/platforms/ios/build/sharedpch
(node:13252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by wf9a5m75** [comment]
How about this?

```
$> cordova platform rm ios

$> cordova platform add ios
```

**Comment by thezakman** [comment]
I did that too before posting.

**Comment by wf9a5m75** [comment]
Open the project with `xcode`, then `product > clean`

**Comment by thezakman** [comment]
The problem is that I can't open in xcode if it's not finishing the command: ```ionic cordova build ios``

**Comment by wf9a5m75** [comment]
Xcode can clean-up the problem.

**Comment by wf9a5m75** [comment]
Tons of similar reports:
https://www.google.com/search?q=ios+CopyStringsFile

The easiest solution is to remove all language files using xcode.

**Comment by wf9a5m75** [comment]
I figured out the reason. The reason is apostrophe in `ru.lproj` and `uk.lproj`.

I could build your app (cheeper-mapcrashing) with the `multiple_maps` branch code.

**Comment by thezakman** [comment]
Great, I will re-install the plugin.
thank you for the amaizing support and dedication to this plugin!

**Comment by wf9a5m75** [comment]
You are welcome ;)

**Comment by thezakman** [comment]
I can only execute ```ionic cordova build ios --prod`` when I try to run on emulator I've got error ```ionic cordova run ios -lc --target=iPhone-X```

**Comment by thezakman** [comment]
@wf9a5m75 error still persist at build time when copying the files.

**Comment by wf9a5m75** [comment]
Did you reinstall the plugin? I have no problem with that command.
![screen shot 2018-02-26 at 1 30 40 pm](https://user-images.githubusercontent.com/167831/36696533-51ac866e-1af9-11e8-8752-548c5b11ec44.png)

**Comment by battika** [comment]
I have just the same issue. I checked everything on stackoverflow and did what they suggested including removing and readding platform, cleaning cordova and xcode and checking line feed at the end of the localization files but still the same issue. I cannot create an archive for itunes upload any longer. Copy usually fails with the Japanese Russian and Ukranien files so the ones that have different character sets to English. So I forked the plugin removed everything but the base pgm file from the plugin.xml file and it works now.

**Comment by thezakman** [comment]
I think I'll do the same, since i cannot archive either.

**Comment by thezakman** [comment]
@wf9a5m75 I tried but didn't work, still crashes when copying the string files at build time.
as @battika mentioned I tried everything i found on stackoverflow too but no luck.

**Comment by battika** [comment]
@thezakman not sure what your experience is but it fails at random language files for me most of the time. It might be the Russian file for the first run, then the Japanese file for the second run, etc. This is a very strange issue.

I am using XCode version 9.2 on MacOS Sierra.

**Comment by thezakman** [comment]
Me too, what i've done is remove the languages files in order to build with sucesss

**Comment by wf9a5m75** [comment]
How about this project?
https://github.com/mapsplugin/ionic-googlemaps-quickdemo

I have no problem to build the project.

```
$ ionic info

cli packages: (/Users/masashi/.nvm/versions/node/v7.10.0/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v7.10.0
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

```

This is build logs.

```bash
masashi-macgms:ionic-googlemaps-quickdemo masashi$ nvm use 7.10
Now using node v7.10.0 (npm v5.6.0)
masashi-macgms:ionic-googlemaps-quickdemo masashi$ cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="(API_KEY)" --variable API_KEY_FOR_IOS="(API_KEY)"
Adding cordova-plugin-googlemaps to package.json
Saved plugin info for "cordova-plugin-googlemaps" to config.xml
masashi-macgms:ionic-googlemaps-quickdemo masashi$ cordova platform add ios
Using cordova-fetch for cordova-ios@^4.5.3
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: ionic.googlemaps.quickdemo
	Name: GoogleMaps quick demo
iOS project created with cordova-ios@4.5.4
Installing "cordova-plugin-googlemaps" for ios
Installing "com.googlemaps.ios" for ios

            Official document
            https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md
        
Discovered plugin "ionic-plugin-keyboard" in config.xml. Adding it to the project
Failed to restore plugin "ionic-plugin-keyboard" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin ionic-plugin-keyboard@^2.2.1 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
Discovered plugin "cordova-plugin-device" in config.xml. Adding it to the project
Installing "cordova-plugin-device" for ios
Adding cordova-plugin-device to package.json
Saved plugin info for "cordova-plugin-device" to config.xml
Discovered plugin "cordova-plugin-splashscreen" in config.xml. Adding it to the project
Installing "cordova-plugin-splashscreen" for ios
Adding cordova-plugin-splashscreen to package.json
Saved plugin info for "cordova-plugin-splashscreen" to config.xml
Discovered plugin "cordova-plugin-ionic-webview" in config.xml. Adding it to the project
Installing "cordova-plugin-ionic-webview" for ios
Adding cordova-plugin-ionic-webview to package.json
Saved plugin info for "cordova-plugin-ionic-webview" to config.xml
--save flag or autosave detected
Saving ios@~4.5.4 into config.xml file ...
masashi-macgms:ionic-googlemaps-quickdemo masashi$ ionic cordova run ios --simulator
Error: Cannot find module '/Users/masashi/Documents/workspace2/ionic-googlemaps-quickdemo/node_modules/@ionic/app-scripts'
masashi-macgms:ionic-googlemaps-quickdemo masashi$ npm install

> fsevents@1.1.2 install /Users/masashi/Documents/workspace2/ionic-googlemaps-quickdemo/node_modules/fsevents
> node install

[fsevents] Success: "/Users/masashi/Documents/workspace2/ionic-googlemaps-quickdemo/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node" is installed via remote

> node-sass@4.5.3 install /Users/masashi/Documents/workspace2/ionic-googlemaps-quickdemo/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/masashi/.npm/node-sass/4.5.3/darwin-x64-51_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/masashi/Documents/workspace2/ionic-googlemaps-quickdemo/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.5.3 postinstall /Users/masashi/Documents/workspace2/ionic-googlemaps-quickdemo/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/masashi/Documents/workspace2/ionic-googlemaps-quickdemo/node_modules/node-sass/vendor/darwin-x64-51/binding.node
Testing binary
Binary is fine
added 653 packages in 41.061s
masashi-macgms:ionic-googlemaps-quickdemo masashi$ ionic cordova run ios --simulator
[INFO] Running app-scripts build: --platform ios --target cordova
       
[17:58:26]  build dev started ... 
[17:58:26]  clean started ... 
[17:58:26]  clean finished in 3 ms 
[17:58:26]  copy started ... 
[17:58:26]  deeplinks started ... 
[17:58:26]  deeplinks finished in 168 ms 
[17:58:26]  transpile started ... 
[17:58:31]  transpile finished in 4.75 s 
[17:58:31]  preprocess started ... 
[17:58:31]  preprocess finished in 2 ms 
[17:58:31]  webpack started ... 
[17:58:31]  copy finished in 5.22 s 
[17:58:43]  webpack finished in 12.50 s 
[17:58:43]  sass started ... 
[17:58:45]  sass finished in 2.11 s 
[17:58:45]  postprocess started ... 
[17:58:45]  postprocess finished in 19 ms 
[17:58:45]  lint started ... 
[17:58:46]  build dev finished in 19.75 s 
> ionic cordova prepare
> cordova prepare
⠦ Running command [17:58:51]  lint finished in 5.93 s 
✔ Running command - done!
Discovered platform "android@6.3.0" in config.xml or package.json. Adding it to the project
Using cordova-fetch for cordova-android@6.3.0
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: ionic.googlemaps.quickdemo
	Name: GoogleMaps_quick_demo
	Activity: MainActivity
	Android target: android-26
Subproject Path: CordovaLib
Android project created with cordova-android@6.3.0
Installing "com.googlemaps.ios" for android
Installing "cordova-plugin-device" for android
Installing "cordova-plugin-googlemaps" for android
Subproject Path: CordovaLib

            Official document
            https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md
        
Installing "cordova-plugin-ionic-webview" for android
Installing "cordova-plugin-splashscreen" for android
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
          
Discovered plugin "ionic-plugin-keyboard" in config.xml. Adding it to the project
Installing "ionic-plugin-keyboard" for android
Installing "ionic-plugin-keyboard" for ios
> cordova run ios
Building for iPhone X Simulator

Building project: /Users/masashi/Documents/workspace2/ionic-googlemaps-quickdemo/platforms/ios/GoogleMaps quick demo.xcworkspace

	Configuration: Debug

	Platform: emulator
Build settings from command line:
    CONFIGURATION_BUILD_DIR = /Users/masashi/Documents/workspace2/ionic-googlemaps-quickdemo/platforms/ios/build/emulator
    SDKROOT = iphonesimulator11.2
    SHARED_PRECOMPS_DIR = /Users/masashi/Documents/workspace2/ionic-googlemaps-quickdemo/platforms/ios/build/sharedpch

Build settings from configuration file '/Users/masashi/Documents/workspace2/ionic-googlemaps-quickdemo/platforms/ios/cordova/build-debug.xcconfig':
    CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES
    CODE_SIGN_ENTITLEMENTS = $(PROJECT_DIR)/$(PROJECT_NAME)/Entitlements-$(CONFIGURATION).plist
    CODE_SIGN_IDENTITY = iPhone Developer
    ENABLE_BITCODE = NO
    GCC_PREPROCESSOR_DEFINITIONS = DEBUG=1
    HEADER_SEARCH_PATHS = "$(TARGET_BUILD_DIR)/usr/local/lib/include" "$(OBJROOT)/UninstalledProducts/include" "$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include" "$(BUILT_PRODUCTS_DIR)"
    OTHER_LDFLAGS = -ObjC
    SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h

=== BUILD TARGET CordovaLib OF PROJECT CordovaLib WITH CONFIGURATION Debug ===


Check dependencies


Write auxiliary files

/bin/mkdir -p /Users/masashi/Documents/workspace2/ionic-googlemaps-quickdemo/platforms/ios/build/sharedpch/CordovaLib_Prefix-chnbsgicopugjhdayfdwqcadvmnl
write-file /Users/masashi/Documents/workspace2/ionic-googlemaps-quickdemo/platforms/ios/build/sharedpch/CordovaLib_Prefix-chnbsgicopugjhdayfdwqcadvmnl/CordovaLib_Prefix.pch.pch.hash-criteria
write-file /Users/masashi/Library/Developer/Xcode/DerivedData/GoogleMaps_quick_demo-crguamvzkicbrtfkdrwlskussgiq/Build/Intermediates.noindex/CordovaLib.build/Debug-iphonesimulator/CordovaLib.build/Cordova-project-headers.hmap
...
...
...

CodeSign build/emulator/GoogleMaps\ quick\ demo.app
    cd /Users/masashi/Documents/workspace2/ionic-googlemaps-quickdemo/platforms/ios
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/masashi/.nvm/versions/node/v7.10.0/bin:/Users/masashi/google-cloud-sdk/bin:/opt/local/bin:/opt/local/sbin:/Users/masashi/.yarn/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/android-sdk/platform-tools:/android-sdk/build-tools:/android-sdk/tools:/opt/minicom/2.2/bin:/usr/local/mysql/bin/:/android-sdk/platform-tools:/android-sdk/tools:/Users/masashi/bin:/android-sdk/ndk-bundle:/android-sdk/ndk-bundle/toolchains:/infer-osx-v0.1.0/infer/infer/bin"
    
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --timestamp=none /Users/masashi/Documents/workspace2/ionic-googlemaps-quickdemo/platforms/ios/build/emulator/GoogleMaps\ quick\ demo.app

** BUILD SUCCEEDED **

No target specified for emulator. Deploying to iPhone-X, 11.2 simulator

ionic.googlemaps.quickdemo: 17383
logPath: /Users/masashi/Documents/workspace2/ionic-googlemaps-quickdemo/platforms/ios/cordova/console.log

[OK] Your app has been deployed.
     Did you know you can live-reload changes from your app with --livereload?
masashi-macgms:ionic-googlemaps-quickdemo masashi$ 
```

**Comment by thezakman** [comment]
I will try to build tomorrow at work and let you know.

**Comment by Bengejd** [comment]
I fixed this issue by removing: 

`        
        <resource-file src="src/android/res/values-ja/pgm_strings.xml" target="res/values-ja/pgm_strings.xml" />
        
        <resource-file src="src/android/res/values-ru/pgm_strings.xml" target="res/values-ru/pgm_strings.xml" />
        
        <resource-file src="src/android/res/values-uk/pgm_strings.xml" target="res/values-uk/pgm_strings.xml" />
        
        <resource-file src="src/android/res/values-pt-rPT/pgm_strings.xml" target="res/values-pt-rPT/pgm_strings.xml" />
        
        <resource-file src="src/android/res/values-de/pgm_strings.xml" target="res/values-de/pgm_strings.xml" />
        
        <resource-file src="src/android/res/values-fr/pgm_strings.xml" target="res/values-fr/pgm_strings.xml" />`

from the `cordova-plugin-googlemaps` folder in the `plugin.xml` file. Idk why this was cropping up, but it fixed it!

**Comment by battika** [comment]
@Bengejd I did the same thing but it is not a fix but a workaround :)
@wf9a5m75 You need to use `--prod --release` parameters for building then open the project in XCode, do a clean and archive in order to see the issue.

**Comment by wf9a5m75** [comment]
Even I added `--prod --release`, I can't reproduce it

**Comment by wf9a5m75** [comment]
```bash
masashi-macgms:workspace2 masashi$ git clone https://github.com/mapsplugin/ionic-googlemaps-quickdemo

masashi-macgms:workspace2 masashi$ cd ionic-googlemaps-quickdemo

masashi-macgms:ionic-googlemaps-quickdemo masashi$ vim config.xml   <--- replace API keys

masashi-macgms:ionic-googlemaps-quickdemo masashi$ vim package.json   <--- replace API keys

masashi-macgms:ionic-googlemaps-quickdemo masashi$ npm install
> fsevents@1.1.2 install /Users/masashi/Documents/workspace2/ionic-googlemaps-quickdemo/node_modules/fsevents
> node install
...
...
...

masashi-macgms:ionic-googlemaps-quickdemo masashi$ cordova platform list
Error: Current working directory is not a Cordova-based project.

masashi-macgms:ionic-googlemaps-quickdemo masashi$ cordova platform list

masashi-macgms:ionic-googlemaps-quickdemo masashi$ mkdir www

masashi-macgms:ionic-googlemaps-quickdemo masashi$ cordova platform list
Installed platforms:
  
Available platforms: 
  android ~6.3.0
  blackberry10 ~3.8.0 (deprecated)
  browser ~5.0.0
  ios ~4.5.1
  osx ~4.0.1
  ubuntu ~4.3.4 (deprecated)
  webos ~3.7.0
  windows ~5.0.0
  www ^3.12.0

masashi-macgms:ionic-googlemaps-quickdemo masashi$ cordova platform add ios
Using cordova-fetch for cordova-ios@^4.5.4
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: ionic.googlemaps.quickdemo
	Name: GoogleMaps quick demo
iOS project created with cordova-ios@4.5.4
Discovered plugin "ionic-plugin-keyboard" in config.xml. Adding it to the project
Installing "ionic-plugin-keyboard" for ios
Adding ionic-plugin-keyboard to package.json
Saved plugin info for "ionic-plugin-keyboard" to config.xml
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
Discovered plugin "cordova-plugin-device" in config.xml. Adding it to the project
Installing "cordova-plugin-device" for ios
Adding cordova-plugin-device to package.json
Saved plugin info for "cordova-plugin-device" to config.xml
Discovered plugin "cordova-plugin-splashscreen" in config.xml. Adding it to the project
Installing "cordova-plugin-splashscreen" for ios
Adding cordova-plugin-splashscreen to package.json
Saved plugin info for "cordova-plugin-splashscreen" to config.xml
Discovered plugin "cordova-plugin-ionic-webview" in config.xml. Adding it to the project
Installing "cordova-plugin-ionic-webview" for ios
Adding cordova-plugin-ionic-webview to package.json
Saved plugin info for "cordova-plugin-ionic-webview" to config.xml
Discovered plugin "cordova-plugin-googlemaps" in config.xml. Adding it to the project
Installing "cordova-plugin-googlemaps" for ios
Installing "com.googlemaps.ios" for ios

            Official document
            https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md
        
Adding cordova-plugin-googlemaps to package.json
Saved plugin info for "cordova-plugin-googlemaps" to config.xml
--save flag or autosave detected
Saving ios@~4.5.4 into config.xml file ...

masashi-macgms:ionic-googlemaps-quickdemo masashi$ ionic cordova build ios --prod --release --codeSignIdentity="iPhone Developer"
[INFO] Running app-scripts build: --prod --platform ios --target cordova
       
[15:22:41]  build prod started ... 
[15:22:41]  clean started ... 
[15:22:41]  clean finished in 5 ms 
[15:22:41]  copy started ... 
[15:22:41]  deeplinks started ... 
[15:22:42]  deeplinks finished in 398 ms 
[15:22:42]  ngc started ... 
[15:22:53]  ngc finished in 10.64 s 
[15:22:53]  preprocess started ... 
[15:22:53]  preprocess finished in 1 ms 
[15:22:53]  webpack started ... 
[15:22:53]  copy finished in 11.56 s 
[15:23:31]  webpack finished in 38.68 s 
[15:23:31]  uglify started ... 
[15:23:31]  sass started ... 
[15:23:35]  sass finished in 3.76 s 
[15:23:35]  cleancss started ... 
[15:23:37]  cleancss finished in 2.36 s 
[15:24:09]  uglify finished in 37.71 s 
[15:24:09]  postprocess started ... 
[15:24:09]  postprocess finished in 36 ms 
[15:24:09]  lint started ... 
[15:24:09]  build prod finished in 87.75 s 
> ionic cordova prepare
> cordova prepare
✔ Running command - done!

> cordova build ios --release
⠹ Running command [15:24:15]  lint finished in 6.12 s 
✔ Running command - done!
Building project: /Users/masashi/Documents/workspace2/ionic-googlemaps-quickdemo/platforms/ios/GoogleMaps quick demo.xcworkspace
	Configuration: Release
	Platform: device
...
...
...
...
Touch build/device/GoogleMaps\ quick\ demo.app.dSYM
    cd /Users/masashi/Documents/workspace2/ionic-googlemaps-quickdemo/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/masashi/.nvm/versions/node/v7.10.0/bin:/Users/masashi/google-cloud-sdk/bin:/opt/local/bin:/opt/local/sbin:/Users/masashi/.yarn/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/android-sdk/platform-tools:/android-sdk/build-tools:/android-sdk/tools:/opt/minicom/2.2/bin:/usr/local/mysql/bin/:/android-sdk/platform-tools:/android-sdk/tools:/Users/masashi/bin:/android-sdk/ndk-bundle:/android-sdk/ndk-bundle/toolchains:/infer-osx-v0.1.0/infer/infer/bin"
    /usr/bin/touch -c /Users/masashi/Documents/workspace2/ionic-googlemaps-quickdemo/platforms/ios/build/device/GoogleMaps\ quick\ demo.app.dSYM

** ARCHIVE SUCCEEDED **

Exported GoogleMaps quick demo.xcarchive to: /Users/masashi/Documents/workspace2/ionic-googlemaps-quickdemo/platforms/ios/build/device
** EXPORT SUCCEEDED **

```

**Comment by wf9a5m75** [comment]
Ok, I finally figured out the reason in the `fr.lproj/pgm_Localizable.stings`.
French uses apostrophe, but this broken the file format. 
I fixed the file, and of course I confirmed the build process work perfectly.

So, please reinstall the plugin from the multiple_maps branch.

**Comment by thezakman** [comment]
Great, now is fixed!

**Comment by mariohmol** [comment]
Hi there, still having this issue here.. tested everything that were said here..  tryed to debug for some hours.. and is intermitent.. every time gives and error in a different file... to make it work i had to delete all the `<resource-file src="src/ios/strings/de.lproj/pgm_Localizable.strings" target="de.lproj/pgm_Localizable.strings" />`

**Comment by wf9a5m75** [comment]
Please reinstall the plugin v2.2.7

**Comment by xyboox** [comment]
With plugin v2.2.7 I get this on compile:

`2018-03-14 15:01:53.226 xcodebuild[8886:191936]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-13756/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/Runtime/PBXTargetBuildContext.mm:757
Details:  unexpected successful exit code from cancelled command <C0016:'CopyStringsFile pgm_Localizable.strings':P6>
Object:   <PBXTargetBuildContext: 0x7fdb80b51b40>
Method:   -createCommandInvocationRecordFromInvocation:
Thread:   <NSThread: 0x7fdb80d06d70>{number = 9, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2018-03-14 15:01:53.226 xcodebuild[8886:191936]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-13756/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/Runtime/PBXTargetBuildContext.mm:757
Details:  unexpected successful exit code from cancelled command <C0009:'CpResource GoogleMaps.bundle':P6>
Object:   <PBXTargetBuildContext: 0x7fdb80b51b40>
Method:   -createCommandInvocationRecordFromInvocation:
Thread:   <NSThread: 0x7fdb80d06d70>{number = 9, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
** ARCHIVE FAILED **`

**Comment by wf9a5m75** [comment]
In order to reproduce your issue, please share your project files on GitHub.

**Comment by yuyinitos** [comment]
Even with plugin v2.2.7 I still get the build error for iOS. The error seems random on one or more of the language files.

First build:
`The following build commands failed:
	CopyStringsFile build/emulator/goMICE.app/pgm_Localizable.strings goMICE/Resources/hi.lproj/pgm_Localizable.strings`

Second build: 
`The following build commands failed:
	CopyStringsFile build/emulator/goMICE.app/pgm_Localizable.strings goMICE/Resources/ar.lproj/pgm_Localizable.strings`

Third build:
`The following build commands failed:
	CopyStringsFile build/emulator/goMICE.app/pgm_Localizable.strings goMICE/Resources/Base.lproj/pgm_Localizable.strings
	CopyStringsFile build/emulator/goMICE.app/pgm_Localizable.strings goMICE/Resources/pt-BR.lproj/pgm_Localizable.strings
	CopyStringsFile build/emulator/goMICE.app/pgm_Localizable.strings goMICE/Resources/hi.lproj/pgm_Localizable.strings`

**Comment by wf9a5m75** [comment]
No contribution, no help

**Comment by yuyinitos** [comment]
Ok, fair enough.

**Comment by wf9a5m75** [comment]
update: cordova-plugin-googlemaps@2.2.8 solves the ios building problem completely.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add cordova-plugin-googlemaps@2.2.8 --variable ...
```
