### ISSUE TITLE
Ionic: map disappearing and/or unexpected animation on tab switching

### ISSUE THREAD

**Issue by mahnuh** [mapsplugin/cordova-plugin-googlemaps#2166]
**I'm submitting a ...**
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**
- [x] **Android**
- [x] **iOS**

**cordova information:**

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-googlemaps 2.2.8 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

````
"@ionic-native/core": "4.5.3",
"@ionic-native/google-maps": "^4.6.0",
````
**Current behavior:**
When switching the tab in an Ionic app and then switching back to the tab with the map, the map sometimes disappears or does an unexpected animation from top left to bottom right. If you scroll in the other tab the map always disappears. After switching tabs a couple of times the map re-appears with the unexpected animation. See the following screen capture and demo code.

**Expected behavior:**
The map not disappearing at least, best case no animation.

**Screen capture or video record:**
http://sharedby.manuel-heidrich.com/qgdiFE/dP4alTDAOU

**Related code, data or error log (please format your code or data):**
https://github.com/mahnuh/cordova-google-maps-issue-demo

**Comment by wf9a5m75** [comment]
Sorry, the support for ionic-native/google-maps is suspended currently.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2162

**Comment by mahnuh** [comment]
@wf9a5m75 Any idea if you will be able to smooth things out with the ionic team shortly? We have a couple of apps depending on your plugin and at the moment they all are kind of broken because of this issue.

Some additional insights:

- We were able to reproduce the same issue on Android as well.
- Inspecting the view ui hierarchy in xcode shows that the GoogleMapsViewController disappears entirely, see the following screenshots.

http://sharedby.manuel-heidrich.com/rGW7Eq/gwmIPx7dtw
http://sharedby.manuel-heidrich.com/fSUeuX/w4tF1ymXQt

**Comment by wf9a5m75** [comment]
Could you make an apk tentatively?

**Comment by mahnuh** [comment]
@wf9a5m75 here is the apk, but I was not able to test it as I do not have an Android device at home: http://sharedby.manuel-heidrich.com/J32O2b/CANsCwvmPm

**Comment by wf9a5m75** [comment]
The issue didn't occur on my phone at all.

**Comment by wf9a5m75** [comment]
It's midnight in the U.S. anyway, I will see the code tomorrow.

**Comment by mahnuh** [comment]
@wf9a5m75 Thanks for your help so far and have a good night! ;-)

**Comment by wf9a5m75** [comment]
Okay, I figured out the reason.

### REASON:

The about page (that contains a map) size is `0` at the moment.

### DESCRIPTION:

When you are switching tab pages from A to B, the ionic uses `fade in/fade out` transitions (`fading out` for A, `fading in` for B).

Because of this, there are two pages in very short moment. 

If page A has `<div id="map_canvas">`, and page B also has `<div id="map_canvas">`, `getElementById("map_canvas")` returns the `<div id="map_canvas">` of page A.
But after soon, the `<div id="map_canvas">` of page A is gone very after soon, thus map is not rendered. 

In order to prevent this error, the `@ionic-native/google-maps` waits until `document.querySelector(".show-page  #map_canvas")` returns a DOM element.

https://github.com/ionic-team/ionic-native-google-maps/blob/e9b274c6846b1751930c3181313f3515bf08e975/src/%40ionic-native/plugins/google-maps/index.ts#L2041-L2059

I inspected your demo app, and I noticed that the tab page size is `0` when the map is disappeared for some reason.

![screen shot 2018-03-25 at 12 03 19 am](https://user-images.githubusercontent.com/167831/37872625-754fc49c-2fc0-11e8-97c8-9bcd0fe088ec.png)
![screen shot 2018-03-25 at 12 03 15 am](https://user-images.githubusercontent.com/167831/37872628-7a302d76-2fc0-11e8-859d-c27b3e65c802.png)

This is the reason.

### SOLUTION:

Not ready yet.

**Comment by wf9a5m75** [comment]
Please reinstall the plugin from the multiple_maps branch.

The map is disappeared problem should be gone.
![2166](https://user-images.githubusercontent.com/167831/37873124-99b6e130-2fca-11e8-8af9-ab680b1c1a5d.gif)

**Comment by mahnuh** [comment]
Yes, the map won't disappear anymore! Just the funny animation remains.
But at least my apps are not broken anymore, thank you so much for the fast fix and your awesome plugin @wf9a5m75 !

**Comment by wf9a5m75** [comment]
Regarding of the unexpected animation, this occurs because the about page tab is `display: none`.
In this case, the map div is `{left: 0, top: 0, width:0, height: 0}`.
The plugin moves the map view at the position and the size.
After that, when you show the about page, the map view moves to the same position and size with the map div. Thus, unexpected animation.

I updated the plugin code to handle this case more better.
When the plugin detects the map div is `display: none`, the plugin detaches the map view automatically.

![2166](https://user-images.githubusercontent.com/167831/37888612-35a2cb60-307d-11e8-8057-c737853bc05d.gif)

**Comment by wf9a5m75** [comment]
Okay, the unexpected animation is fixed.
![2166](https://user-images.githubusercontent.com/167831/38000855-74ff60e0-31de-11e8-89fe-cc112eb47b65.gif)

**Comment by aMUSiC** [comment]
I know this ticket is closed but I'd like to mention that this will still happen in 2.2.9 (even more prominently) if you change the clickable state of the map (with map.setClickable(true/false)) , push another page into the stack an then go back to the page with the map.

I used to have setClickable(false) onPageLeave and setClickable(true) onPageEnter when I was using an older version of multiple_maps, as it ensured that the map wouldn't highjack the touches on other pages, but now that the plugin has better detection, removing the setClickable() calls gets rid of the unwanted map animation. Still worth mentioning though.

Another strange behavior was in 2.2.8, with this unwanted animation thing happening only on iOS (android worked perfectly), but if I attached safari's debugger on my app running in iOS, the unwanted animation wouldn't happen!!

**Comment by wf9a5m75** [comment]
As I explained above, you need to install multiple_maps branch.

**Comment by gregavola** [comment]
@wf9a5m75 Is it possible to confirm what version this was merge in to master with?

**Comment by wf9a5m75** [comment]
@gregavola I said please make a new issue with your project files.

**Comment by zack403** [comment]
Please i need help, my map too dissappears when ever i navigate away from the page map and come back
