### ISSUE TITLE
map.getCameraPosition() returns undefined

### ISSUE THREAD

**Issue by b4tch** [mapsplugin/cordova-plugin-googlemaps#2184]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-custom-config 2.0.3 "cordova-custom-config"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-admobpro-firebase 2.30.1 "AdMob Plugin Pro"
cordova-plugin-extension 1.5.4 "Cordova Plugin Extension"
cordova-plugin-file 4.1.1 "File"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-firebase 0.1.25 "Google Firebase Plugin"
cordova-plugin-geolocation 2.1.0 "Geolocation"
cordova-plugin-googlemaps 2.3.0-beta-20180327-1354 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.0 "InAppBrowser"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.7 "SocialSharing"
cordova-sqlite-ext 0.10.1 "Cordova sqlite storage plugin with extras (xx dev version branch)"
uk.co.workingedge.phonegap.plugin.launchnavigator 3.2.1 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
When running
```
var cameraPosition = map.getCameraPosition();
```
(after instantiating 'map'), cameraPosition = undefined

**Expected behavior:**
Return an object as per the documentation.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**
I have tried the master branch, old masters (2.2.1 and 2.2.8), and the #multiple_maps branch.  All have the same problem in my code.  I am trying to upgrade from v1.4 to v2.2.9 so have changed my code from using a callback in map.getCameraPosition to receiving the return value from it (but it is always undefined).

**Comment by wf9a5m75** [comment]
You need to use `cordova-plugin-googlemaps 2.2.9`. This is already fixed issue in v2.2.8.
https://github.com/mapsplugin/cordova-plugin-googlemaps#release-notes

**Comment by b4tch** [comment]
I had already tried that version. I've just tried again and the problem remains.

**Comment by b4tch** [comment]
I've fixed my issue, though I am not exactly sure why it was an issue.  I had a function to return the map object:

```
function getMap() {
	var mapDiv = document.getElementById("map_canvas");
	return plugin.google.maps.Map.getMap( mapDiv );
}
```

Every time I wanted to interact with the map, I would call ```var map = getMap();``` and in v1.4 there was no problem.  To resolve this, I just made my map variable global.

**Comment by wf9a5m75** [comment]
Okay, please the project file that reproduce your issue 100% on github.
