### ISSUE TITLE
Ionic Cordova Run Android - Java Error

### ISSUE THREAD

**Issue by shaunthomson2097** [mapsplugin/cordova-plugin-googlemaps#2394]
**I'm submitting a ...**
- [ ] question
- [X ] any problem or bug report

**OS:**  (check one with "x")
- [X ] **Android**
- [ ] **iOS**

**cordova information:**

```
cordova-android-play-services-gradle-release 1.4.3 "cordova-android-play-services-gradle-release"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.3.10 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.0.2 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core : ^4.11.0
@ionic-native/google-maps : ^4.9.1
```

**Current behavior:**

Run the command "ionic cordova run android" (The error occurs when I run the command to build to a device or emulator).

**Expected behavior:**

The APP should build to the android device without error.

**Screen capture or video record:**

![cordova-plugin-googlemaps java error](https://user-images.githubusercontent.com/16734301/44052900-4be0f106-9f3e-11e8-81a2-f5d6cd22ce5c.PNG)

**Comment by wf9a5m75** [comment]
This is already fixed issue. Please reinstall the plugin from the multiple_maps branch.

**Comment by shaunthomson2097** [comment]
Hi

I installed the multi maps version "cordova plugin add
https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps". and
still get the same error. Please advise
Quick install

   - *Stable version(npm)*

$> cordova plugin add cordova-plugin-googlemaps \
    --variable API_KEY_FOR_ANDROID="..." \
    --variable API_KEY_FOR_IOS="..."


   - *Development version(beta version)*

$> cordova plugin add
https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps
\
    --variable API_KEY_FOR_ANDROID="..." \
    --variable API_KEY_FOR_IOS="..."


Kind Regards
Shaun

**Comment by wf9a5m75** [comment]
what's error?

**Comment by shaunthomson2097** [comment]
Hi

The same error as before. Please see attached screenshot.

Kind Regards
Shaun

**Comment by wf9a5m75** [comment]
It means you don't install the plugin from the multiple_maps branch.

**Comment by shaunthomson2097** [comment]
Hi

Please forgive me if I don't understand, but do I run the following command
to install the multi maps branch? (This is the command that I run. Please
see below. Sorry to waist your time. Thank you for your support.)

$> cordova plugin add
https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps
\
    --variable API_KEY_FOR_ANDROID="..." \
    --variable API_KEY_FOR_IOS="..."

**Comment by shaunthomson2097** [comment]
Hi

If you could please indicate which command I should run that would be
appreciated greatly.

**Comment by wf9a5m75** [comment]
If you can't solve the problem by yourself, please share your project files on github, like this repo.
https://github.com/mapsplugin/HelloGoogleMap

**Comment by wf9a5m75** [comment]
Do you think I miss `final`?

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/92f897617cf4957d86bcb35f36a034296508b17b/src/android/plugin/google/maps/PluginGroundOverlay.java#L420
![screen shot 2018-08-13 at 1 29 23 pm](https://user-images.githubusercontent.com/167831/44056382-ed8aa7e6-9efc-11e8-948e-7f1baec15dd7.png)

**Comment by shaunthomson2097** [comment]
Hi Masashi

Then it might be me who is a noob because it was still not final on my side
I had to add it. Thus this means I did not install the correct version.

I sincerely apologize to you from my side.

I will double check the install version and get back to you.

Kind Regards
Shaun

**Comment by wf9a5m75** [comment]
I just published new version as `v2.3.11`. Please try v2.3.11.

**Comment by shaunthomson2097** [comment]
Hi Masashi

I installed the "
https://github.com/mapsplugin/cordova-plugin-googlemaps.git#multiple_maps"
repo plugin, and cannot build android. Now getting another error which
after debugging it seems to be a Cradle error as if the plugin requires a
specific version of gradle. I have gathered as much information for you as
possible if it would assist you.

When I remove your plugin then android builds without error. When I add
your plugin again it fails with the same error.

Error Example:
/////////////////////////////////////////////////////
BUILD START
/////////////////////////////////////////////////////
> cordova run android
Android Studio project detected
ANDROID_HOME=C:\development\android-sdk\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_111
studio
Subproject Path: CordovaLib
Subproject Path: app
publishNonDefault is deprecated and has no effect anymore. All variants are
now published.
Configuration 'compile' in project ':app' is deprecated. Use
'implementation' instead.
The Task.leftShift(Closure) method has been deprecated and is scheduled to
be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at
build_1ej6fmeb94pnvci9snzvj7grm.run(C:\APPS\iyeza-express-Rider-app\platforms\android\app\build.gradle:144)
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:prepareLintJar UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:platformAttrExtractor UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:javaPreCompileDebug UP-TO-DATE
:CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
:CordovaLib:processDebugJavaRes NO-SOURCE
:CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug
UP-TO-DATE
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:compileDebugAidl UP-TO-DATE
:CordovaLib:packageDebugRenderscript NO-SOURCE
:app:compileDebugRenderscript UP-TO-DATE
:app:checkDebugManifest UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:prepareLintJar UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:createDebugCompatibleScreenManifests UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:splitsDiscoveryTaskDebug UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:javaPreCompileDebug UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk NO-SOURCE
:app:compileDebugSources UP-TO-DATE
:CordovaLib:mergeDebugShaders UP-TO-DATE
:CordovaLib:compileDebugShaders UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets
:app:transformClassesWithStackFramesFixerForDebug UP-TO-DATE
:app:transformClassesWithDesugarForDebug UP-TO-DATE
:app:transformClassesWithDexBuilderForDebug UP-TO-DATE
:app:transformDexArchiveWithExternalLibsDexMergerForDebug UP-TO-DATE
:app:transformDexArchiveWithDexMergerForDebug UP-TO-DATE
:CordovaLib:compileDebugNdk NO-SOURCE
:CordovaLib:mergeDebugJniLibFolders UP-TO-DATE
:CordovaLib:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
:CordovaLib:transformNativeLibsWithStripDebugSymbolForDebug UP-TO-DATE
:CordovaLib:transformNativeLibsWithIntermediateJniLibsForDebug UP-TO-DATE
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
:app:transformNativeLibsWithStripDebugSymbolForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task
':app:transformNativeLibsWithStripDebugSymbolForDebug'.
> A problem occurred starting process 'command
'C:\development\android-sdk\sdk\ndk-bundle\toolchains\mips64el-linux-android-4.9\prebuilt\windows-x86_64\bin\mips64el-linux-android-strip''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or
--debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
45 actionable tasks: 2 executed, 43 up-to-date
(node:15616) UnhandledPromiseRejectionWarning: Error: cmd: Command failed
with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task
':app:transformNativeLibsWithStripDebugSymbolForDebug'.
> A problem occurred starting process 'command
'C:\development\android-sdk\sdk\ndk-bundle\toolchains\mips64el-linux-android-4.9\prebuilt\windows-x86_64\bin\mips64el-linux-android-strip''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or
--debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
    at ChildProcess.whenDone
(C:\APPS\iyeza-express-Rider-app\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

C:\APPS\iyeza-express-Rider-app>
/////////////////////////////////////////////////////
BUILD END
/////////////////////////////////////////////////////

[image: cordova-plugin-googlemaps Gradle Error Multi Maps Branch.PNG]

Kind Regards
Shaun

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/troubleshootings/mips64el-linux-android-strip/README.md

**Comment by shaunthomson2097** [comment]
Hi Masashi

I made the changes that were in the readme file link you sent me and also
had to change thecordova distribution URL in the StudioBuilder.js file.

Now it is building!

I just wanted to thank you so much for assisting me all the way.

You are a true legend.

Kind Regards
Shaun
