### ISSUE TITLE
Support WKWebView and Cordova iOS version 4.0.0

### ISSUE THREAD

**Issue by BozzaDaniel** [mapsplugin/cordova-plugin-googlemaps#685]
Recently a development version (4.0.0) of Cordova iOS added support for WKWebView with the help of an installable plugin (UIWebView is also a plugin but it's included by default). Read more about everything here: https://shazronatadobe.wordpress.com/2015/09/09/apache-cordova-ios-4-0-0-and-wkwebview-support/

The plugin isn't compatible with the latest API changes (https://github.com/apache/cordova-ios/blob/master/guides/API%20changes%20in%204.0.md), the errors are these:

Incompatible pointer types assigning to 'UIWebView *' from 'UIView * _Nullable' 
No known instance method for selector 'initWithWebView:'
No visible @interface for 'UIView' declares the selector 'stringByEvaluatingJavaScriptFromString:'
'Cordova/CDVJSON.h' file not found

Shouldn't be too hard to make it compatible with version 4.0, I can modify the plugin files to fix these myself, but it would be nice to use an unmodified plugin.

**Comment by Hirbod** [comment]
Please provide a PR in it's that easy. The API changes looking huge, I guess there has to be done some work (writeJavascript, UIWebview, Nsbase64 etc)

**Comment by BozzaDaniel** [comment]
I managed to make the code compile without issues. I encountered an issue with making the map actually appear though as the webpage background stays white. 

I've even tried creating a brand new project with Cordova iOS 3.9.1 and the stable version of this plugin to see if there is some issue with the WKWebView but now the background stays white even here. I can't figure out why it's impossible to set a transparent background on the webview anymore.

**Comment by Hirbod** [comment]
We need to figure out if its possible. I don't have any knowledge about WKWebView.

**Comment by Hirbod** [comment]
http://stackoverflow.com/questions/27211561/transparent-background-wkwebview-nsview

**Comment by BozzaDaniel** [comment]
I managed to get a transparent background of the WKWebView when using the plugin version with a local server on 3.9.1, but when I updated to 4.0.0 and went without the local server I could no longer set the background to transparent. So it should be possible to make the background transparent on a WKWebView. 

I tried to create a new Cordova project (3.9.1) and the stable version of this plugin and now it worked to create a transparent background for the WebView. I haven't a clue as why it didn't work earlier. 

I will check now if I can get the plugin working with the server version of WKWebView.

**Comment by Hirbod** [comment]
Thanks a lot !

**Comment by BozzaDaniel** [comment]
I believe I got it to work with Cordova iOS 4.0.0 and WKWebView plugin without a server. Will try on a clean project next week to see if it works on that too. Next up is enabling all JS stuff again as stringByEvaluatingJavaScriptFromString no longer exists in WKWebView. it should be replaced by evaluateJavascript. Would probably be smart to create a method that is able to switch between the two depending on what is available than littering the code with ifs.

**Comment by Hirbod** [comment]
Yeah, that would be nice. Thanks for your work, I really appreciate it. My time is very limited.

**Comment by BozzaDaniel** [comment]
I got it working with a clean project too. The fix for the transparency issue is done by using [self.webView [setOpacity:NO]] and [self.webView [setBackgroundColor:[UIColor clearColor]]] in the viewDidLoad method of the viewcontroller displaying the map. Doing it in any other place doesn't seem to work.

I don't know if it's preferable to use self.webViewEngine.engineWebView instead of self.webView on cordova ios 4.0.0 as they've reworked the internals of cordova quite a bit.

**Comment by BozzaDaniel** [comment]
Started working on this again today, and I've found an issue. When working with WKWebViews Cordova has done some changes with the JS bridge communication using postMessage. This causes an error when trying to pass and object with functions. The solution to this is simply to remove the functions that is sent to the native side from all objects.

The biggest issue is the LatLng object that contains 3 functions. they need to be removed in order for anything involving them to work.

Stripping functions shouldn't cause an issue when using UIWebViews as those are ignored by the native side anyway.

**Comment by gregavola** [comment]
@BozzaDaniel Any chance you can post your edited googlemaps-cdv-plugin.js file so I take a look at what you edited?

**Comment by jaredgreener** [comment]
I am getting a DataCloneError: DOM Exception 25 when adding markers to the map in wkwebview

**Comment by BozzaDaniel** [comment]
@gregavola My quick fix was simply commenting out the functions in the LatLng class. That is a bad idea though so you should probably do something like this, untested:
```javascript
function delete_from_object( object, type ) {
    var keys = Object.keys(object);
    for( var key in keys ) {
        if ( typeof object[key] === 'object' ) {
            object[key] = delete_from_object( object[key], type );
        } else if ( typeof object[key] === type ) {
            delete object[key];
        }
    }
    return object;
}
```
Then before doing cordova.exec you'd simply do:
```javascript
options = delete_from_object( options, 'function' );
```

**Comment by Hirbod** [comment]
@BozzaDaniel any progress on this?

**Comment by BozzaDaniel** [comment]
Stopped working on this for a couple of weeks while working on some other projects. When I return to working on this I will fix everything for the project targeting iOS 8 and above. I've returned to working with a local web server as XHRs to file-urls are still blocked in iOS 9.

**Comment by Hirbod** [comment]
@BozzaDaniel Cordova iOS 4.0.0 and the wkwebview-engine is out. Would be nice if you could get this plugin work with the new version

**Comment by joewoodhouse** [comment]
Any update on this @BozzaDaniel ? I really want to try this on my current project (which needs a performance boost!) and I'm happy to start from scratch myself but if you've got some work already done would be good to start from there.

**Comment by BozzaDaniel** [comment]
I've been doing some work on this the past few days, and I've found a way to keep it compatible with both webview types: UIWebView and WKWebView:

First, in all places where a webView is defined as a UIWebView has been changed to a UIView instead (as is the case for Cordova iOS 4.0).
Next up is replacing every stringByEvaluatingJavaScriptFromString with a respondsToSelector and performSelector check. Using stringByEvaluatingJavaScriptFromString for UIWebView and evaluateJavaScript:completionHandler: for WKWebView (completionHandler can be nil).

For places where you are getting a property of the webView (such as request.URL) I'm using an NSInvocation, here is Marker.m: 
```objectivec
-(void)setIcon_:(GMSMarker *)marker iconProperty:(NSDictionary *)iconProperty:
   pluginResult:(CDVPluginResult *)pluginResult
     callbackId:(NSString*)callbackId {
// ...
    if (iconPath) {
        NSError *error;
        NSRange range = [iconPath rangeOfString:@"://"];
        if (range.location == NSNotFound) {
            range = [iconPath rangeOfString:@"www/"];
            if (range.location == NSNotFound) {
                range = [iconPath rangeOfString:@"/"];
                if (range.location != 0) {
                    iconPath = [NSString stringWithFormat:@"./%@", iconPath];
                }
            }
        }
        
		range = [iconPath rangeOfString:@"./"];
        if (range.location != NSNotFound) {
			SEL requestSelector = NSSelectorFromString(@"request");
			SEL urlSelector = NSSelectorFromString(@"URL");
			NSString *currentPath = @"";
			if ([self.mapCtrl.webView respondsToSelector:requestSelector]) {
				NSInvocation *invocation = [NSInvocation invocationWithMethodSignature:[[self.mapCtrl.webView class] instanceMethodSignatureForSelector:requestSelector]];
				[invocation setSelector:requestSelector];
				[invocation setTarget:self.mapCtrl.webView];
				[invocation invoke];
				NSURLRequest *request;
				[invocation getReturnValue:&request];
				currentPath = [request.URL absoluteString];
			} else if ([self.mapCtrl.webView respondsToSelector:urlSelector]) {
				NSInvocation *invocation = [NSInvocation invocationWithMethodSignature:[[self.mapCtrl.webView class] instanceMethodSignatureForSelector:urlSelector]];
				[invocation setSelector:urlSelector];
				[invocation setTarget:self.mapCtrl.webView];
				[invocation invoke];
				NSURL *URL;
				[invocation getReturnValue:&URL];
				currentPath = [URL absoluteString];
			}
// ...
```
You'd want to use NSInvocation anytime you access a property of the WebView as it's now defined as a UIView instead. You'd have to check the difference between UIWebView and WKWebView properties too.

One final change is the googlemaps-cdv-plugin.js file: Before running any command with cordova.exec run the following on the properties being sent with type being set to function :
```javascript
function delete_from_object( object, type ) {
	if ( object === null ) return object;
	var keys = Object.keys(object);
	for( var index in keys ) {
	   var key = keys[index];
		if ( typeof object[key] === 'object' ) {
			object[key] = delete_from_object( object[key], type );
		} else if ( typeof object[key] === type ) {
			delete object[key];
		}
	}
	return object;
}
```
run it as so:
```javascript
options = delete_from_object( options, 'function' );
```

These should be all the changes needed to get it to work with WKWebViews.

**Comment by Hirbod** [comment]
So you like to provide a working PR for that. I'll post 100$ on this

**Comment by BozzaDaniel** [comment]
Give me a few days to do it, I need to setup a new project to do the changes properly.

**Comment by joewoodhouse** [comment]
@BozzaDaniel Awesome looking forward to it. Should we re-open this issue (not sure why it was ever closed?)

**Comment by Telemakhos** [comment]
+1 for reopening. This is a critical issue.

**Comment by BozzaDaniel** [comment]
Almost done with the changes on a clean project. The last remaining bit is making the webview transparent again. - (void)webViewDidFinishLoad:(UIWebView*)theWebView; has been removed and I need to find the proper way of doing it now. I already fixed it in my own project as I create webviews in a different ways.

**Comment by joewoodhouse** [comment]
Any update on this? Sorry for being impatient, but I'm really looking forward to this feature! :)

**Comment by jvence** [comment]
Same here. This is critical to my app. Any updates

**Comment by aesmon** [comment]
@BozzaDaniel your repo works great on Meteor 1.3 with WkWebView. Are you still working on the plugin? Great work by the way, really amazing.

**Comment by gauravarora** [comment]
@BozzaDaniel Sorry for yet another not-so-helpful reminder but is there any chance you're still working on this?

**Comment by johnrobertcobbold** [comment]
Just caught up on Cordova4 and this thread. Anything that we can do to help you @BozzaDaniel ?

**Comment by jvence** [comment]
I guess not much happening on this issue. Has anyone try using a different solution such as Leaflet or OpenLayers?

**Comment by aesmon** [comment]
@jvence BozzaDaniel's repo works great on WkWebView, no problems encountered

**Comment by jvence** [comment]
@aesmon Thanks for the update. I guess the following should work:

cordova plugin add https://github.com/BozzaDaniel/cordova-plugin-googlemaps.git --variable API_KEY_FOR_ANDROID="...." --variable API_KEY_FOR_IOS="..."  and I should ignore:

"Notice: plugin.google.maps has been automatically converted to cordova-plugin-googlemaps and fetched from npm. This is due to our old plugins registry shutting down."

**Comment by aesmon** [comment]
@jvence I'd just add the plugin manually. I am running BozzaDaniel's plugin version on Meteor 1.3 with changes to CDVNotifications in the plugin on my local repo. Try specifying the commit or branch after hashtag, or try adding the plugin manually with changes to repo paths in plugin.xml and package.json

**Comment by gauravarora** [comment]
Out of curiosity, why not use something like mapbox or leaflet instead? I
ask because the author has clearly said that he does not have the time to
update the plugin which effectively means this is the last version.

**Comment by jvence** [comment]
@gauravarora I agree doesn't seem that there's going to be good ongoing development on this plugin. I think the problem with Leaflet and others i that it is javascript based and uses bitmaps instead of vector drawing and you probably lack the caching and other functionality built into Google maps.

**Comment by aesmon** [comment]
@gauravarora Pretty much what jvence said, while JavaScript is pretty efficient in with JIT compiler on WkWebView, the rendering and bandwidth usage is far greater than native SDK. You can observe this when panning and zooming in/out on both instances. Native SDK fetches vector data that weighs very little and draws the map while JavaScript fetches whole image tiles. You can observe the gray spots while waiting to load the image tiles while native SDK you can hardly notice rendering and it looks much smoother. I have first used GM api v3 for my project, but then found the feel and performance of this plugin to be way superior, also tried mapbox.

**Comment by jvence** [comment]
@gauravarora @aesmon I guess it also depends on how you're using maps. We've been testing MapBox and we're very happy with the performance so far and will probably end up switching as it provides lots of capabilities not available in GM and this plug-in.

**Comment by denisbabineau** [comment]
@jvence what platform/vebview have you tested MapBox on? I'm particularly interested in any quirks/issues it may have with crosswalk on android and WKWebView on ios.

**Comment by Hirbod** [comment]
Please use Gitter for that. This isn't a chat - it is an issue tracker. I've deleted non related posts

**Comment by denisbabineau** [comment]
to avoid the problem mentioned by @jvence (plugin.google.maps has been automatically converted), looks like the plugin/package should be renamed to cordova-plugin-googlemaps to avoid the remapping performed by the cordova-registry-mapper package; I haven't looked up which cordova version introduced this mapper but it prevents doing a plugin add with repo url to test this feature/branch and requires manual/local install.

**Comment by twavis** [comment]
I downloaded @BozzaDaniel 's repo locally and changed the id to cordova-plugin-googlemaps and finally was able to build the app in meteor (release 1.3-beta.11) using wkwebview. 

The map seems to load but it is white background where map should be. Not sure what to do now.

@aesmon did you change anything else in getting it to work with meteor 1.3?

**Comment by aesmon** [comment]
@twavis From what I recall, I don't think "CDVPageDidLoadNotification" was ever fired in GoogleMaps.m in Meteor 1.3 as it's turned off by default. Either turn it on in Meteor files or paste the pageDidLoad handlers directly into pluginInitialization which seems to not produce any errors for me so far. Also, if you are using any framework like Meteoric Ionic with position absolute views then you will have to set them to transparent manually in JS when initializing the map.

**Comment by jsanta** [comment]
@twavis what did you do to change the plugin id? what files did you change?

I also downloaded @BozzaDaniel 's repo and tried installing it with ionic plugin add /local/repo --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..." but it is going to bitbucket to download the plugin.

**Comment by denisbabineau** [comment]
@jsanta you can look at my branch which has BozzaDaniel's fork merged in with the latest and the plugin id renamed. I also changed the com.googlemaps.ios dependency commit reference to point to a specific commits (ideally this would point to a tag) since Meteor does not accept branch specs (only hashes and tags to be explicit). Note that with this branch I'm experiencing the white background on IOS issue as well but I haven't looked at the CDVPageDidLoadNotification workaround/fix that BozzaDaniel & easmon mentioned (yet).

**Comment by jsanta** [comment]
Thanks @denisbabineau I'll give it a try.
Best regards.

**Comment by jsanta** [comment]
@denisbabineau seems to work OK, at least the device is showing the map and the app is not complaining because of any errors.

**Comment by denisbabineau** [comment]
Update: See my comments in Pull #807 to fix whitescreen issues in ios if you need this right away. Hopefully will get merged/pulled soon.

**Comment by johnrobertcobbold** [comment]
Is @BozzaDaniel 's repo also working on cordova-ios 4+ with uiwebview ?

**Comment by wf9a5m75** [comment]
@BozzaDaniel Thank you for your great pull request.

I merged #807 into the master branch. If there is any error that related with #807, please leave the comment here.

**Comment by mscheffer** [comment]
i found this thread today, MONTHS after it was started, the problem still seems to be there, unless i'm not getting the correct version ?

**Comment by fairport** [comment]
Same here !!  Identical situation
Xcode 7.3.1 Cordova 6.2.0  
plugin.google.maps 1.3.9 "phonegap-googlemaps-plugin"  (downloaded 2 hours ago)

.../platforms/ios/<appname>/Plugins/plugin.google.maps/GoogleMaps.m:176:59: **No known instance method for selector 'initWithWebView:'**

**Comment by Hirbod** [comment]
Npm Version has no WKWebview Support. Download directly from master
